import 'package:flutter/material.dart';

class Model {
  String? name;
  String? email;
  int? age;
  bool? gender;
  String? img;
  Model? model;

  Model({this.img, this.name, this.email, this.age, this.gender, this.model});
}

List<Model> myList = [
  Model(
    img: 'images/shakil.jpg',
    name: 'Shakil',
    email: 'shakilwell0@gmail.com',
    age: 22,
    gender: true,
  ),
  Model(
    img: 'images/tisha.jpg',
    name: 'Tisha',
    email: 'tisha0@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/jannat.jpg',
    name: 'Jannat',
    email: 'jannat@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/shakil.jpg',
    name: 'Shakil',
    email: 'shakilwell0@gmail.com',
    age: 22,
    gender: true,
  ),
  Model(
    img: 'images/tisha.jpg',
    name: 'Tisha',
    email: 'tisha0@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/jannat.jpg',
    name: 'Jannat',
    email: 'jannat@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/shakil.jpg',
    name: 'Shakil',
    email: 'shakilwell0@gmail.com',
    age: 22,
    gender: true,
  ),
  Model(
    img: 'images/tisha.jpg',
    name: 'Tisha',
    email: 'tisha0@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/jannat.jpg',
    name: 'Jannat',
    email: 'jannat@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/shakil.jpg',
    name: 'Shakil',
    email: 'shakilwell0@gmail.com',
    age: 22,
    gender: true,
  ),
  Model(
    img: 'images/tisha.jpg',
    name: 'Tisha',
    email: 'tisha0@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/jannat.jpg',
    name: 'Jannat',
    email: 'jannat@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/shakil.jpg',
    name: 'Shakil',
    email: 'shakilwell0@gmail.com',
    age: 22,
    gender: true,
  ),
  Model(
    img: 'images/tisha.jpg',
    name: 'Tisha',
    email: 'tisha0@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/jannat.jpg',
    name: 'Jannat',
    email: 'jannat@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/shakil.jpg',
    name: 'Shakil',
    email: 'shakilwell0@gmail.com',
    age: 22,
    gender: true,
  ),
  Model(
    img: 'images/tisha.jpg',
    name: 'Tisha',
    email: 'tisha0@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/jannat.jpg',
    name: 'Jannat',
    email: 'jannat@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/shakil.jpg',
    name: 'Shakil',
    email: 'shakilwell0@gmail.com',
    age: 22,
    gender: true,
  ),
  Model(
    img: 'images/tisha.jpg',
    name: 'Tisha',
    email: 'tisha0@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/jannat.jpg',
    name: 'Jannat',
    email: 'jannat@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/shakil.jpg',
    name: 'Shakil',
    email: 'shakilwell0@gmail.com',
    age: 22,
    gender: true,
  ),
  Model(
    img: 'images/tisha.jpg',
    name: 'Tisha',
    email: 'tisha0@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/jannat.jpg',
    name: 'Jannat',
    email: 'jannat@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/shakil.jpg',
    name: 'Shakil',
    email: 'shakilwell0@gmail.com',
    age: 22,
    gender: true,
  ),
  Model(
    img: 'images/tisha.jpg',
    name: 'Tisha',
    email: 'tisha0@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/jannat.jpg',
    name: 'Jannat',
    email: 'jannat@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/shakil.jpg',
    name: 'Shakil',
    email: 'shakilwell0@gmail.com',
    age: 22,
    gender: true,
  ),
  Model(
    img: 'images/tisha.jpg',
    name: 'Tisha',
    email: 'tisha0@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/jannat.jpg',
    name: 'Jannat',
    email: 'jannat@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/shakil.jpg',
    name: 'Shakil',
    email: 'shakilwell0@gmail.com',
    age: 22,
    gender: true,
  ),
  Model(
    img: 'images/tisha.jpg',
    name: 'Tisha',
    email: 'tisha0@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/jannat.jpg',
    name: 'Jannat',
    email: 'jannat@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/shakil.jpg',
    name: 'Shakil',
    email: 'shakilwell0@gmail.com',
    age: 22,
    gender: true,
  ),
  Model(
    img: 'images/tisha.jpg',
    name: 'Tisha',
    email: 'tisha0@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/jannat.jpg',
    name: 'Jannat',
    email: 'jannat@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/shakil.jpg',
    name: 'Shakil',
    email: 'shakilwell0@gmail.com',
    age: 22,
    gender: true,
  ),
  Model(
    img: 'images/tisha.jpg',
    name: 'Tisha',
    email: 'tisha0@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/jannat.jpg',
    name: 'Jannat',
    email: 'jannat@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/shakil.jpg',
    name: 'Shakil',
    email: 'shakilwell0@gmail.com',
    age: 22,
    gender: true,
  ),
  Model(
    img: 'images/tisha.jpg',
    name: 'Tisha',
    email: 'tisha0@gmail.com',
    age: 22,
    gender: false,
  ),
  Model(
    img: 'images/jannat.jpg',
    name: 'Jannat',
    email: 'jannat@gmail.com',
    age: 22,
    gender: false,
  ),
];
